font_size 12.0
font_family      family="RobotoMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor #cccccc 
cursor_shape beam
cursor_shape_unfocused hollow 
scrollback_fill_enlarged_window yes
wheel_scroll_multiplier 7.0

trip_trailing_spaces yes

background_opacity 0.8
editor code
notify_on_cmd_finish unfocused
confirm_os_window_close 0
