font_family   FiraCode Nerd Font
font_size 11.0

cursor #cccccc 
cursor_shape beam
cursor_shape_unfocused hollow 
scrollback_fill_enlarged_window yes
wheel_scroll_multiplier 7.0

trip_trailing_spaces yes

background_opacity 0.8
editor code
notify_on_cmd_finish unfocused
confirm_os_window_close 0
