#! /bin/bash

ddcutil --bus 7 --skip-ddc-checks --sleep-multiplier=.1 setvcp 10 "$@"
value=$(ddcutil --bus 7 --skip-ddc-checks --sleep-multiplier=.1 --brief getvcp 10 | grep -oP "C \K\d+")
echo "$value" > ~/.config/last_brightness
notify-send Brightness "$value" -h string:x-canonical-private-synchronous:osd
