theme = "catppuccin_mocha"

[editor]
cursorline = true
preview-completion-insert = false
rulers = [ 80 ]
color-modes = true
trim-trailing-whitespace = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
